Now checking whether a valid number was provided and exiting code accordingly

diff --git a/create-solution-folder b/create-solution-folder
--- a/create-solution-folder
+++ b/create-solution-folder
@@ -103,6 +103,12 @@ function checkInputCommand(){
     else
         toLowercase language
     fi
+
+    isPositiveInteger $problemNumber
+    if [[ $? = 0 ]]; then
+        echo "Error: Invalid number provided"
+        helper
+    fi
     
     tester
 }
